# Generated by Django 4.1.5 on 2023-01-26 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='item_id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('url', models.CharField(max_length=50, unique=True, verbose_name='url')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.item', verbose_name='parent_id')),
            ],
        ),
    ]
